#First stage image
FROM composer:1.6.5 as build
WORKDIR /app
COPY ./ /app

#install application dependecies from the lock file
RUN composer install \
  --optimize-autoloader \
  --no-interaction \
  --no-progress

# continue stage build with the desired image and copy the source including the
# dependencies downloaded by composer
FROM php:7.4-apache

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_mysql

# set env vars
ENV APP_NAME "Travellist"
ENV APP_ENV "dev"
# $ python -c 'import base64; import os; print(base64.encodestring(os.urandom(32)))'
ENV APP_KEY base64:REPLACE_WITH_RANDOM_BASE64_ENCODED_STRING
ENV APP_DEBUG true
#ENV APP_URL http://localhost:8000

ENV LOG_CHANNEL "stack"

ENV DB_CONNECTION "mysql"
#ENV DB_HOST XX.XXX.XXXX.XX
#ENV DB_PORT 3306
ENV DB_DATABASE "REPLACE_WITH_CLOUD_SQL_MYSQL_DB_NAME"
ENV DB_USERNAME "REPLACE_WITH_CLOUD_SQL_MYSQL_USERNAME"
ENV DB_PASSWORD "REPLACE_WITH_CLOUD_SQL_MYSQL_DB_SUPER_SECRET_PASSWORD"
ENV DB_SOCKET "/cloudsql/REPLACE_WITH_CLOUD_SQL_CONNECTION_NAME"
ENV MYSQL_ATTR_TIMEOUT 5
ENV BROADCAST_DRIVER "log"
ENV CACHE_DRIVER "file"
ENV QUEUE_CONNECTION "sync"
ENV SESSION_DRIVER "cookie"
ENV SESSION_LIFETIME 120

#ENV MAIL_DRIVER "smtp"
#ENV MAIL_HOST "SMTP_HOST"
#ENV MAIL_PORT SMTP_PORT
#ENV MAIL_USERNAME null
#ENV MAIL_PASSWORD null
#ENV MAIL_ENCRYPTION null

#ENV PUSHER_APP_ID 
#ENV PUSHER_APP_KEY 
#ENV PUSHER_APP_SECRET 
#ENV PUSHER_APP_CLUSTER mt1

#ENV MIX_PUSHER_APP_KEY "${PUSHER_APP_KEY}"
#ENV MIX_PUSHER_APP_CLUSTER "${PUSHER_APP_CLUSTER}"

# 8080 port for cloud run
EXPOSE 8080
COPY --from=build /app /var/www/
COPY apache/000-default.conf /etc/apache2/sites-available/000-default.conf
RUN chmod 777 -R /var/www/storage/ \
    && echo "Listen 8080" >> /etc/apache2/ports.conf \
    && chown -R www-data:www-data /var/www/ \
    && a2enmod rewrite
