#
FROM composer:1.6.5 as build
WORKDIR /app
COPY . /app

#install application dependecies from the lock file
RUN composer install

#RUN php artisan key:generate

#
FROM php:7.4-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git curl libpng-dev libonig-dev libxml2-dev \
    zip unzip

# Clear system cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Generate encryption key and set to APP_KEY env var
#RUN php artisan key:generate

# set env vars
ENV APP_NAME "Travellist"
ENV APP_ENV "dev"
# $ python -c 'import base64; import os; print(base64.encodestring(os.urandom(32)))'
ENV APP_KEY "RANDOM_BASE64_ENCODED_STRING"
ENV APP_DEBUG true
#ENV APP_URL http://localhost:8000

ENV LOG_CHANNEL "stack"

ENV DB_CONNECTION "mysql"
#ENV DB_HOST XX.XXX.XXXX.XX
#ENV DB_PORT 3306
ENV DB_DATABASE "CLOUD_SQL_MYSQL_DB_NAME"
ENV DB_USERNAME "CLOUD_SQL_MYSQL_USERNAME"
ENV DB_PASSWORD "CLOUD_SQL_MYSQL_DB_SUPER_SECRET_PASSWORD"
ENV DB_SOCKET "/cloudsql/CLOUD_SQL_CONNECTION_NAME"
ENV MYSQL_ATTR_TIMEOUT 5
ENV BROADCAST_DRIVER "log"
ENV CACHE_DRIVER "file"
ENV QUEUE_CONNECTION "sync"
ENV SESSION_DRIVER "cookie"
ENV SESSION_LIFETIME 120

#ENV MAIL_DRIVER "smtp"
#ENV MAIL_HOST "SMTP_HOST"
#ENV MAIL_PORT SMTP_PORT
#ENV MAIL_USERNAME null
#ENV MAIL_PASSWORD null
#ENV MAIL_ENCRYPTION null

#ENV PUSHER_APP_ID 
#ENV PUSHER_APP_KEY 
#ENV PUSHER_APP_SECRET 
#ENV PUSHER_APP_CLUSTER mt1

#ENV MIX_PUSHER_APP_KEY "${PUSHER_APP_KEY}"
#ENV MIX_PUSHER_APP_CLUSTER "${PUSHER_APP_CLUSTER}"

#
FROM nginx:alpine

# 8080 port for cloud run
EXPOSE 8080
COPY --from=build /app /var/www/
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx","-g","daemon off;"]
